web:
  restart: always
  image: acladmin:latest
  ports:
    - "5580:8080"
  volumes:
# Not needed for test installations. The docker image will put a default configuration there.
#   - /var/local/acladmin:/var/local/acladmin
    - /etc/localtime:/etc/localtime:ro # Share timezone data with host
  environment:
    - CATALINA_OPTS=-Djava.security.egd=file:/dev/./urandom
  hostname: acladmin
